
#--------------------------通用配置-------------------------
spring:
  application:
    # 应用名
    name: comicstar
  profiles:
    # 激活特定配置
    active: dev
  jackson:
    generator:
      # JSON 序列化时，将所有 Number 类型的属性都转为 String 类型返回，避免前端数据精度丢失的问题。
      # 由于 Javascript 标准规定所有数字处理都应使用 64 位 IEEE 754 浮点值完成，
      # 结果是某些 64 位整数值无法准确表示（尾数只有 51 位宽）
      write-numbers-as-strings: true
  servlet:
    multipart:
      # 上传文件最大大小
      max-file-size: 5MB
server:
  # 端口号
  port: 8899

--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://192.168.121.121:3306/comicstar?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root


--- #---------------------中间件配置---------------------------
spring:
  data:
    # Redis 配置
    redis:
      host: 192.168.121.121
      port: 6379
      password: root


  # Elasticsearch 配置
  elasticsearch:
    # 是否开启 Elasticsearch 搜索引擎功能：true-开启 false-不开启
    enabled: true
    uris:
      - https://192.168.121.121:9200
    username: elastic
    password: 7z*to9bN_*YCQHJKgqKm
    ssl:
      # 设置 ssl 的认证模式，如果该配置项为 none ，说明不需要认证，信任所有的 ssl 证书。
      verification-mode: none

  # Spring AMQP 配置
  amqp:
    # 是否开启 Spring AMQP：true-开启 false-不开启
    enabled: false
  # RabbitMQ 配置
  rabbitmq:
    addresses: "amqp://guest:guest@192.168.121.121"
    virtual-host: comicstar
    template:
      retry:
        # 开启重试
        enabled: true
        # 最大重试次数
        max-attempts: 3
        # 第一次和第二次重试之间的持续时间
        initial-interval: "3s"


--- #----------------------安全配置----------------------------



--- #--------------------接口文档配置---------------------------
springdoc:
  api-docs:
    enabled: false

--- #----------------------邮箱配置-----------------------------
#邮箱服务器
spring:
  mail:
    host: smtp.qq.com
    #发件人昵称
    nickname: pigeoncat
    #邮箱账户
    username: 3580341883@qq.com
    #邮箱第三方授权码
    password: xbtbmswjjjaxvhuussddbii
    #编码类型
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

--- #---------------------自定义配置----------------------------
comicstar:
  # 跨域配置
  cors:
    # 允许跨域的域名
    allow-origins:
      - http://192.168.121.121:1025
      - http://192.168.121.121:8080
      - http://192.168.121.121
      - http://www.comicstaropen.com
      - http://comicstaropen.com
  # JWT密钥
  jwt:
    secret: E66559580A1ADF48CKK920516062F12E
  # XSS 过滤配置
  xss:
    # 过滤开关
    enabled: true
    # 排除链接
    excludes:
      - /system/notice/*
  file:
    # 文件上传配置
    upload:
      # 上传路径
      path: /Users/pigeoncat/upload




--- #------------------- dev 特定配置---------------------------
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    enabled: true

--- #------------------- test 特定配置--------------------------
spring:
  config:
    activate:
      on-profile: test

--- #-------------------- prod 特定配置-------------------------
spring:
  config:
    activate:
      on-profile: prod
  data:
    # Redis 配置
    redis:
      host: 192.168.121.121
      port: 6379
      password: root


